mongodb:
  host: 127.0.0.1
  port: 27017
  username: flautim
  password: -------
  db: flautim
kubernetes:
  config_path: '~/.kube/config'
  namespace: default
  pvc: my-pvc-nfs
  image: 'sufex00/flautin:trainer-0.1'